### PR TITLE
Device Tree View fix

### PR DESCRIPTION
**Pull request by ninioe**
I fixed the device tree view and combined all the latest updates

### CODE REVIEW

**Comment by ninioe** [comment]
before
image

after:
image

**Comment by ninioe** [comment]
Hi Anton,
Please don't marge this pull request yet because the selected device focus is not working ok, I will continue working on this on Sunday...

**Comment by tananaev** [comment]
Do you realize that this pull request is to your own master branch, not official Traccar repo? I don't receive any notifications about it because it's inside your repo.

**Comment by tananaev** [comment]
Also, I want to know exact difference between my old implementation and your one.

**Pull request closed without merging**
